-- ANIMAL_OUTS 테이블의 ANIMAL_ID는 ANIMAL_INS의 ANIMAL_ID의 외래 키
-- 입양을 간 기록은 있는데, 보호소에 들어온 기록이 없는 동물의 ID와 이름을 ID 순으로 조회

SELECT A2.ANIMAL_ID, A2.NAME
FROM ANIMAL_INS AS A1
RIGHT JOIN ANIMAL_OUTS AS A2
    ON A1.ANIMAL_ID = A2.ANIMAL_ID
WHERE A1.DATETIME IS NULL
ORDER BY ANIMAL_ID;