-- ANIMAL_OUTS 테이블의 ANIMAL_ID는 ANIMAL_INS의 ANIMAL_ID의 외래 키
-- 입양을 간 동물 중, 보호 기간이 가장 길었던 동물 두 마리의 아이디와 이름을 조회 (보호 기간이 긴 순으로 조회)
SELECT A1.ANIMAL_ID, A1.NAME
FROM ANIMAL_INS AS A1
INNER JOIN ANIMAL_OUTS AS A2
    ON A1.ANIMAL_ID = A2.ANIMAL_ID
ORDER BY A2.DATETIME-A1.DATETIME DESC
LIMIT 2;