-- ANIMAL_OUTS 테이블의 ANIMAL_ID는 ANIMAL_INS의 ANIMAL_ID의 외래 키입니다.
-- 아직 입양을 못 간 동물 중, 가장 오래 보호소에 있었던 동물 3마리의 이름과 보호 시작일을 조회
SELECT A1.NAME,	A1.DATETIME
FROM ANIMAL_INS AS A1
LEFT JOIN ANIMAL_OUTS AS A2
    ON A1.ANIMAL_ID = A2.ANIMAL_ID
WHERE A2.ANIMAL_ID IS NULL
ORDER BY A1.DATETIME
LIMIT 3;